### ISSUE TITLE
the new tango module name is already in used by another project...

### ISSUE THREAD

**Issue by picca** [tango-cs/pytango#29]
Hello guyes,if you look at pypi you will see that the tango module name spaces,is already used.

https://pypi.python.org/pypi/Tango/0.2.7

from tango.factory.app import build_app
app = build_app('sitename')

I do not know the pypi policy about module namespace, ownership.

but htis is a real problem...

cheers

Frederic

**Comment by birkenfeld** [comment]
As far as I know, there's no PyPI policy about what's in the distributions and who "owns" a namespace (I assume that the distribution of PyTango wouldn't be renamed, just the module/Python package inside).

Of course there would be a file conflict between the packages, but that's more an issue of policy in Linux distributions that provide packages for both Tango and PyTango. The Tango package is probably not packaged by distributions and appears unmaintained (last release 4 years ago).

**Comment by vxgmichel** [comment]
Exactly. The idea is to mimic the naming convention of other binding projects such as PyZMQ:
- Project: PyTango
- Repo: pytango
- PyPI: pytango
- Python module: tango 

This change has been discussed with Tiago and Jairo during the last pytango meeting. 
Do you see any issue with that (apart from this other unrelated tango package)?

**Comment by picca** [comment]
Here the information relatives to the python module namespaces

http://legacy.python.org/dev/peps/pep-0423/#top-level-namespace-relates-to-code-ownership

**Comment by birkenfeld** [comment]
Note that PEP 423 is not implemented, but deferred, as such it is just a proposal by its author.

Also, the wording "As an example, don't use "apache" as top-level namespace: "Apache" is the name of an existing project (in the case of "Apache", it is also a trademark)." seems to favor PyTango belonging to Tango, which is much older than the web framework.

**Comment by tiagocoutinho** [comment]
I followed the Pypi tango project web page (http://willowtreeapps.com/). It seems to be a commercial company and the project seems to be abandoned since they have no mention of it in their web page and the last release is from 2012. It is a shame that Pypi is filled with these dead projects.

Pypi trusts project owners to keep their project up to date (including removal if they are not supported anymore). I don't think this pypi project prevents pytango from exporting the `tango` namespace but we could always try to contact the company and try to convince them to redraw their pypi project.

I agree with @vxgmichel concerning the naming.

@picca, do you have any intention of renaming the debian package to `python-tango` ?

**Comment by tiagocoutinho** [comment]
Can we consider that the name clash is not a show stopper and close this issue?

**Comment by vxgmichel** [comment]
Agreed!

**Comment by picca** [comment]
Hello

came back from holidays :))

> @picca<https://github.com/picca>, do you have any intention of renaming the debian package to python-tango ?

If the module is now tango -> python-tango

so Yes the binary package should be renamed.
